name: NodeJS with Next.js

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Choose a single version for simplicity, or adjust as needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Environment Variables
        run: |
          echo "ASSET_PREFIX=/<your-repo-name>" >> .env.local
          echo "BASE_PATH=/<your-repo-name>" >> .env.local

      - name: Install Dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build

      - name: Export App
        run: npm run export

      - name: Create .nojekyll File
        run: touch ./out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
