name: NodeJS with Next.js

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Environment Variables
        env:
          ASSET_PREFIX: /<your-repo-name>
          BASE_PATH: /<your-repo-name>
        run: |
          echo "" > .env.local
          echo ASSET_PREFIX=$ASSET_PREFIX >> .env.local
          echo BASE_PATH=$BASE_PATH >> .env.local

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js (using Next's build command)
        run: npm run build

      - name: Export app (if static export is required)
        run: npm run export

      - name: Create .nojekyll
        run: touch ./out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: gh-pages/deploy@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_branch: gh-pages
          build_dir: ./out
